---
- name: Setup OS
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml

  tasks:
    # From here https://itsfoss.com/vim-8-release-install/
    - name: Add (more actual) apt repository for VIM
      ansible.builtin.apt_repository:
        repo: ppa:jonathonf/vim
      become: yes
      tags:
        - apt

    - name: Install apt packages
      ansible.builtin.apt:
        pkg: {{ apt_packages }}
        state: latest
        update_cache: yes
      become: yes
      tags:
        - apt

